#!/usr/bin/python

from simple_db_migrate.cli import CLI
from simple_db_migrate.main import Main

(options, args) = CLI().parse()

# If CLI was correctly parsed, execute db-migrate.
Main(options, args).execute()