#!/usr/bin/python

from simple_db_migrate.cli import CLI
from simple_db_migrate.core import Config
from simple_db_migrate.main import Main

(options, args) = CLI().parse()

# Create config
config = Config(options.config_file)
config.put("schema_version", options.schema_version)
config.put("show_sql", options.show_sql)
config.put("show_sql_only", options.show_sql_only)
config.put("new_migration", options.new_migration)
config.put("drop_db_first", options.drop_db_first)

# If CLI was correctly parsed, execute db-migrate.
Main(config).execute()